### ISSUE TITLE
Support for multiple displays

### ISSUE THREAD

**Issue by tarya-systeam** [philippnormann1337/xrandr-brightness-script#2]
Hi,

This is a cool script that does its job, but it's hard coded to the first display found by xrandr. If we provide the second connected display as a second argument, it will still using the brightness value of the first display.

I suggest the following changes, if you like this, please commit:

#!/bin/sh
USAGE() {
echo '#############################################'
echo "Please provide two arguments."
echo "First should be - or +"
echo "Second should be a name of connected display"
echo
echo "Please see the list of connected displays:"
xrandr -q|grep -w connected|awk '{print $1}'
echo '#############################################'
}

if xrandr -q | grep -o $2 &>/dev/null && (($# == 2)) && [[ $1 =~ ^(\+|\-)$ ]]; then
	
CURRBRIGHT=$(xrandr -q --verbose|grep -A 5 $2|awk '/Brightness/ {print $NF}')
if  [ -z $CURRBRIGHT ]; then
	echo "Current brightness for provided display has an empty value. Is this display connected?"
	echo "Please see the list of connected displays:"
	xrandr -q|grep -w connected|awk '{print $1}'
	exit 1
	else
	if [ "$1" = "+" ] && [ $(echo "$CURRBRIGHT < 1" | bc) -eq 1 ] 
	then
	xrandr --output $2 --brightness $(echo "$CURRBRIGHT + 0.1" | bc)
	elif [ "$1" = "-" ] && [ $(echo "$CURRBRIGHT > 0" | bc) -eq 1 ] 
	then
	xrandr --output $2 --brightness $(echo "$CURRBRIGHT - 0.1" | bc)
	fi
fi
else 
USAGE
fi

**Comment by tarya-systeam** [comment]
script will work only with #!/bin/bash shebang header

**Comment by philippnormann** [comment]
@tarya-systeam Thanks fo the suggestion! 👍
I got around to implementing something similar in the latest commit https://github.com/philippnormann1337/xrandr-brightness-script/commit/06defc124b4cf515e5a848cd6d5f7f7483cf2cf7
