### ISSUE TITLE
Feature Request - Noob

### ISSUE THREAD

**Issue by ajkothari13** [philippnormann1337/xrandr-brightness-script#3]
Hi, Thanks a lot for sharing this script. I am trying to control brightness on Ubuntu 18.04, having nvidia 710 graphics card on a desktop.

Is it possible to combine your script with some keyboard shortcut (for ex. ctrl+up, ctrl+dn) to control brightness.

If it is already possible with your script, would you be kind enough and guide on how to achieve it?

Many thanks in advance!
~ajay

**Comment by navjay** [comment]
Hey mate, I used this script in arch for my X1Y2 OLED, and I believe you can bind it to any key you wish - I bound it to my fn+f5 and fn+f6 keys. I can't remember specifics, but I suggest looking up how to bind keys to a script in ubuntu and using that method. Just bind the brightness script with relevant arguments to the key that you wish.

**Comment by philippnormann** [comment]
Thanks @navjay for taking your time to answer this question!
As @navjay explained it is possible to bind this script to any keyboard shortcut you wish.
This functionality is not directly part of the script, but is instead enabled by most desktop environments, which allow binding custom keyboard shortcut to bash commands.
A guide on how to achieve this under ubuntu can be found [here](https://help.ubuntu.com/stable/ubuntu-help/keyboard-shortcuts-set.html.en).
